spring:
  datasource:
    url: jdbc:mysql://localhost:30306/test
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
app:
  currency: eur
apis:
  wallet-value-api: https://api.blockcypher.com/v1/{{coin.symbol}}/main/addrs/{{wallet.address}}/balance
  coin-value-api: https://www.bitstamp.net/api/v2/ticker/{{coin.symbol}}{{app.currency}}/